// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvwsopmlmpbwvelexlbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2d3NvcG1sbXBid3ZlbGV4bGJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNTgwNTUsImV4cCI6MjA1NDkzNDA1NX0.JxeP2U4FoX4K2iJZeujOw4rK8jWmSjyOjenzs9_ab98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);